feat: impl `wallet_` namespace
paradigmxyz/alphanet pull request #129
Opened 2024-10-04 01:26 UTC by onbjerg

2024-10-07 22:34 UTC, onbjerg commented on crates/wallet/src/lib.rs
> +            match request.to {
cleaning this up before going out of draft

2024-10-07 22:44 UTC, onbjerg commented on crates/wallet/src/lib.rs
> +        }
it's both auth and eip-1559, can move some stuff into a validation func for things that are shared

2024-10-08 11:50 UTC, mattsse requested changes

2024-10-08 11:50 UTC, mattsse commented on Cargo.toml
> +    "optimism",
this can be removed with latest reth

2024-10-08 11:50 UTC, mattsse commented on crates/wallet/src/lib.rs
> +        );
I think you can use from_iter([]) here

2024-10-08 11:50 UTC, mattsse commented on crates/wallet/src/lib.rs
> +                let state = self.provider.latest().unwrap();
this should be handled gracefully

2024-10-08 13:01 UTC, mattsse approved these changes

2024-10-08 13:01 UTC, mattsse commented on crates/wallet/src/lib.rs
> +            .map_err(Into::into)
we should log the error here, because this can fail if we're out of funds for example or out of txpool slots

2024-10-08 13:25 UTC, merged